service: speech-nlp-backend
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
plugins:
  - serverless-offline
package:
  include:
  - lib/**

functions:
  speak:
    handler: handler.speak
    events:
    - http:
        path: speak
        method: post
        cors: true
  processTemp:
    handler: handler.processTemp
    events:
    - http:
        path: process
        method: post
        cors: true
