service: speech-nlp-backend

custom:
  secrets: ${file(./secrets.json)}
  authorizer:
    name: authorizer
    arn: ${self:custom.secrets.COGNITO_ARN}
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    NOSQL_TABLE_NAME: ${self:custom.secrets.NOSQL_TABLE_NAME}
plugins:
  - serverless-offline
  - serverless-bundle
package:
  include:
  - lib/**

functions:
  speak:
    handler: handler.speak
    events:
    - http:
        path: speak
        method: post
        cors: true
  processTemp:
    handler: handler.processTemp
    events:
    - http:
        path: process
        method: post
        cors: true
  createDocument:
    handler: document.create
    events:
    - http:
        path: /doc
        method: post
        authorizer: ${self:custom.authorizer}
        cors: true

